<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="laser_frame_offset_x" value="0.36"/>  <!-- Length and offset is specified in Meters -->
    <xacro:property name="laser_frame_offset_z" value="1.253"/>
    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_length" value="0.04"/>
    <xacro:property name="lidar_mass" value="0.5"/>
    <xacro:property name="lidar_cylinder_stand_radius" value="0.025"/>
    <xacro:property name="lidar_cylinder_stand_length" value="0.3"/>
    <xacro:property name="lidar_cylinder_stand_mass" value="1"/> 


    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="${laser_frame_offset_x} 0 ${laser_frame_offset_z}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <!-- LIDAR -->
        <visual>
            <origin xyz="0 0 ${lidar_length / 2}"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${lidar_length / 2}"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_length}" radius="${lidar_radius}">
            <origin xyz="0 0 ${lidar_length / 2}"/>
        </xacro:inertial_cylinder>

        <!-- LIDAR CYLINDER STAND -->
        <visual>
            <origin xyz="0 0 ${-lidar_cylinder_stand_length / 2}"/>
            <geometry>
                <cylinder radius="${lidar_cylinder_stand_radius}" length="${lidar_cylinder_stand_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${-lidar_cylinder_stand_length / 2}"/>
            <geometry>
                <cylinder radius="${lidar_cylinder_stand_radius}" length="${lidar_cylinder_stand_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_cylinder_stand_mass}" length="${lidar_cylinder_stand_length}" radius="${lidar_cylinder_stand_radius}">
            <origin xyz="0 0 ${-lidar_cylinder_stand_length / 2}"/>
        </xacro:inertial_cylinder>
    </link>



    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>